//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_X_rols
    {
        public long id { get; set; }
        public byte rolId { get; set; }
        public long userId { get; set; }
    
        public virtual rol rol { get; set; }
        public virtual user user { get; set; }
    }
}
