//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateKeys
{
    using System;
    using System.Collections.Generic;
    
    public partial class key
    {
        public byte id { get; set; }
        public byte[] C_Key { get; set; }
        public byte[] C_IV { get; set; }
    }
}
